import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "375px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      nav: "1180px",
    },
    extend: {
      colors: {
        /** Deep slate: primary brand, heroes, legal strip */
        brand: "#1C3044",
        "brand-mid": "#2A4158",
        /** Burgundy: accents, CTAs, highlights */
        accent: "#7A4050",
        "accent-light": "#9E5A6A",
        "accent-muted": "#EDE4E6",
        /** Sage: secondary accent, editorial details */
        sage: "#5A7D6A",
        "sage-light": "#E4ECE7",
        charcoal: "#5A6570",
        mist: "#EEF1F4",
        line: "#D8DEE4",
        heading: "#1C3044",
        body: "#3D4A56",
        parchment: "#F9F7F2",
        /** Legacy aliases — mapped to new palette for gradual migration */
        navy: "#1C3044",
        gold: "#7A4050",
        "gold-light": "#9E5A6A",
        "gold-muted": "#EDE4E6",
        cream: "#F9F7F2",
        "section-alt": "#EEF1F4",
      },
      fontFamily: {
        serif: ["var(--font-fraunces)"],
        sans: ["var(--font-public-sans)"],
        display: ["var(--font-fraunces)"],
      },
      borderRadius: {
        card: "2px",
      },
      boxShadow: {
        card: "0 1px 8px rgba(28, 48, 68, 0.06)",
        "card-hover": "0 4px 18px rgba(28, 48, 68, 0.1)",
        header: "0 1px 0 rgba(28, 48, 68, 0.08)",
      },
      backgroundImage: {
        "hero-gradient": "linear-gradient(135deg, #1C3044 0%, #2A4158 100%)",
        "hero-diagonal":
          "linear-gradient(115deg, transparent 55%, rgba(90, 125, 106, 0.12) 55%, rgba(90, 125, 106, 0.06) 100%)",
      },
      minHeight: {
        touch: "44px",
      },
      minWidth: {
        touch: "44px",
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-parchment",
    "bg-cream",
    "bg-page",
    "bg-hero-gradient",
    "bg-hero-diagonal",
    "bg-section-alt",
    "bg-mist",
    "bg-brand",
    "bg-brand-mid",
    "bg-accent",
    "bg-accent-light",
    "bg-accent-muted",
    "bg-sage",
    "bg-sage-light",
    "bg-gold",
    "bg-gold-light",
    "bg-gold-muted",
    "text-accent",
    "text-accent-light",
    "text-gold",
    "text-gold-light",
    "text-body",
    "text-heading",
    "text-charcoal",
    "text-brand",
    "text-navy",
    "text-sage",
    "border-accent",
    "border-accent/40",
    "border-accent/50",
    "border-accent/60",
    "border-brand",
    "border-sage",
    "border-gold",
    "border-gold/40",
    "border-gold/50",
    "border-gold/60",
    "border-line",
    "border-line/80",
    "divide-line",
    "border-accent-light",
    "border-gold-light",
    "shadow-card",
    "shadow-card-hover",
    "shadow-header",
    "rounded-card",
    "hover:shadow-card-hover",
    "hover:border-accent",
    "hover:border-gold",
    "hover:border-gold/40",
    "hover:bg-accent-light",
    "hover:bg-gold-light",
    "hover:text-accent",
    "hover:text-accent-light",
    "hover:text-gold",
    "hover:text-gold-light",
    "hover:text-brand",
    "hover:text-navy",
    "hover:bg-accent/10",
    "hover:bg-gold/10",
    "hover:bg-accent-muted",
    "hover:bg-gold-muted",
    "focus-visible:ring-accent",
    "focus-visible:ring-gold",
    "focus-visible:ring-accent-light",
    "focus-visible:ring-gold-light",
  ],
};

export default config;
