/**
 * Generates public/sitemap.xml and public/robots.txt from the app URL inventory.
 * Run: npm run seo:generate
 */
import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import {
  buildPublicUrlInventory,
  getSitemapChangeFreq,
  getSitemapPriority,
} from "../lib/seo/publicUrlInventory";
import { SITE_URL } from "../lib/site";

const PUBLIC_DIR = join(process.cwd(), "public");

function todayUtc(): string {
  return new Date().toISOString().slice(0, 10);
}

function renderSitemap(): string {
  const inventory = buildPublicUrlInventory();
  const lastmod = todayUtc();

  const urls = inventory.allUrls
    .map((loc) => {
      const path =
        loc === SITE_URL ? "/" : loc.replace(SITE_URL, "") || "/";
      return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${getSitemapChangeFreq(path)}</changefreq>
    <priority>${getSitemapPriority(path).toFixed(2)}</priority>
  </url>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function renderRobots(): string {
  return `# Generated by scripts/generate-seo.ts. Do not edit by hand.
User-agent: *
Allow: /

Disallow: /thank-you
Disallow: /privacy
Disallow: /terms
Disallow: /cookies
Disallow: /contact
Disallow: /api/
Disallow: /.netlify/

Sitemap: ${SITE_URL}/sitemap.xml
`;
}

function main() {
  mkdirSync(PUBLIC_DIR, { recursive: true });
  writeFileSync(join(PUBLIC_DIR, "sitemap.xml"), renderSitemap(), "utf8");
  writeFileSync(join(PUBLIC_DIR, "robots.txt"), renderRobots(), "utf8");
  const count = buildPublicUrlInventory().allUrls.length;
  console.log(`Wrote public/sitemap.xml (${count} URLs)`);
  console.log("Wrote public/robots.txt");
}

main();
